const FETCH_ALL_BOOK = 'FETCH_ALL_BOOK';
const ADD_BOOK = "ADD_BOOK";
const FETCH_A_BOOK = "FETCH_A_BOOK";
const DELETE_BOOK = "DELETE_BOOK"

export { FETCH_ALL_BOOK, ADD_BOOK, FETCH_A_BOOK, DELETE_BOOK };